### ISSUE TITLE
runnin mondrian process on AML data notebook

### ISSUE THREAD

**Issue by AlexBouz** [disiji/fc_mondrian#1]
Greetings, thanks for sharing your code, i was trying to run the mondrian process from the flowMP-AML-run notebook on the AML dataset but got stuck (see screenshot), any comment is appreciated!

![Classification](https://user-images.githubusercontent.com/37419030/66341468-5e77b800-e915-11e9-81b1-d0e2fd31669f.png)
![Classification 2](https://user-images.githubusercontent.com/37419030/66341603-a0086300-e915-11e9-9320-fb2762808aa3.png)

**Comment by disiji** [comment]
Hi, thanks for your interest in our work. Two issues here:
1. I used Python2 instead of Python3, where "print" can be used as a statement instead of a function. If you prefer to run the notebook with python3 kernel, the first thing you need to do is to replace all "print XXX" with "print(XXX)"
2. "MP_mcmc" was imported from "src". 
Let me know if my reply is not clear to you.

**Comment by AlexBouz** [comment]
Dear @disiji thank you for your quick reply. I realized i was using the repository fc_differentiable in my first message, so i switched to the good one fc_mondrian but i could not load flowCompute_mp (see screenshots). I added the os path and it generated more errors. I tried this from the downloaded repo and  the cloned one. Any guidance is appreciated for your classification method!
![Adding path](https://user-images.githubusercontent.com/37419030/66348011-8bcb6280-e923-11e9-9b09-46274c0f0a00.png)
![downloaded repo](https://user-images.githubusercontent.com/37419030/66348134-db119300-e923-11e9-8159-3207c371a787.png)

**Comment by disiji** [comment]
Hi, fc_differentiable is the repo for our new work "Optimization of Automated Gating for Clinical Diagnosis using Discriminative Gates." It is in press and will be published in Cytometry A.

As for the errors you show, it is the same error in your previous message. As shown in the upper right corner of your browser, you are running the notebook with a Python3 kernel, where "print XXX" is not supported. I just changed all print statements to make it executable in python3. Please pull again and see how it goes. Let me know if there is anything else I can do.

**Comment by AlexBouz** [comment]
Dear @disiji thank you for the support, i was able to run the mondrian process now
![modrian](https://user-images.githubusercontent.com/37419030/66357689-d9ed5f80-e93d-11e9-8579-898cf6790060.png)

**Comment by disiji** [comment]
Please cite us if you find it related :)

```
@inproceedings{ji2018bayesian,
  title={Bayesian Trees for Automated Cytometry Data Analysis},
  author={Ji, Disi and Nalisnick, Eric and Qian, Yu and Scheuermann, Richard H and Smyth, Padhraic},
  booktitle={Machine Learning for Healthcare Conference},
  pages={465--483},
  year={2018}
}
```
